/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubsequentQueriesRouteImport } from './routes/subsequent-queries'
import { Route as SimpleSiblingQueriesRouteImport } from './routes/simple-sibling-queries'
import { Route as IndexRouteImport } from './routes/index'

const SubsequentQueriesRoute = SubsequentQueriesRouteImport.update({
  id: '/subsequent-queries',
  path: '/subsequent-queries',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleSiblingQueriesRoute = SimpleSiblingQueriesRouteImport.update({
  id: '/simple-sibling-queries',
  path: '/simple-sibling-queries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simple-sibling-queries': typeof SimpleSiblingQueriesRoute
  '/subsequent-queries': typeof SubsequentQueriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simple-sibling-queries': typeof SimpleSiblingQueriesRoute
  '/subsequent-queries': typeof SubsequentQueriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simple-sibling-queries': typeof SimpleSiblingQueriesRoute
  '/subsequent-queries': typeof SubsequentQueriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simple-sibling-queries' | '/subsequent-queries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simple-sibling-queries' | '/subsequent-queries'
  id: '__root__' | '/' | '/simple-sibling-queries' | '/subsequent-queries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimpleSiblingQueriesRoute: typeof SimpleSiblingQueriesRoute
  SubsequentQueriesRoute: typeof SubsequentQueriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subsequent-queries': {
      id: '/subsequent-queries'
      path: '/subsequent-queries'
      fullPath: '/subsequent-queries'
      preLoaderRoute: typeof SubsequentQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-sibling-queries': {
      id: '/simple-sibling-queries'
      path: '/simple-sibling-queries'
      fullPath: '/simple-sibling-queries'
      preLoaderRoute: typeof SimpleSiblingQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimpleSiblingQueriesRoute: SimpleSiblingQueriesRoute,
  SubsequentQueriesRoute: SubsequentQueriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
