[tool.poetry]
name = "vector-importer"
version = "0.1.0"
description = "Vector importer script"
authors = ["Convex, Inc. <no-reply@convex.dev>"]


[tool.poetry.dependencies]
python-dotenv = "^1.0.0"
python = "~3.9"
convex = {path = "../../../crates/convex", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

venv = ".venv"

[tool.poetry.scripts]
main = "vector-importer.main:main"

