[tool.poetry]
name = "text-importer"
version = "0.1.0"
description = "Vector importer script"
authors = ["Convex, Inc. <no-reply@convex.dev>"]


[tool.poetry.dependencies]
python-dotenv = "^1.0.0"
python = "~3.9"
convex = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

venv = ".venv"

[tool.poetry.scripts]
main = "text-importer.main:main"

