name: Test and lint
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  check:
    name: Test and lint
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Node setup
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "20.20.2"

      - name: NPM v10
        run: npm install -g npm@10 --registry=https://registry.npmjs.org

      - name: Format check (dprint)
        uses: dprint/check@9cb3a2b17a8e606d37aae341e49df3654933fc23 # v2.3
        with:
          config-path: dprint.json
          dprint-version: "0.51.1"

      - run: npm i

      - run: npm run test-esm

      - run: npm run lint
