/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/teams/{team_id}/create_project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create project
         * @description Create a new project on a team, optionally provisioning a dev or prod
         *     deployment.
         */
        post: operations["create project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/list_projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description List all projects for a team.
         */
        get: operations["list projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/list_deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deployments
         * @description List deployments for a projects.
         */
        get: operations["list deployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get deployment in project by id
         * @description Get a deployment within a project by reference, default production
         *     deployment, or default dev deployment for the calling user.
         */
        get: operations["get deployment in project by project id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id_or_slug}/projects/{project_slug}/deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get deployment in project by slug
         * @description Get a deployment within a project identified by team and project slug,
         *     by reference, default production deployment, or default dev deployment
         *     for the calling user.
         */
        get: operations["get deployment in project by project slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete project
         * @description Delete a project. Deletes all deployments in the project as well.
         */
        post: operations["delete project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project by ID
         * @description Get a project by its ID.
         */
        get: operations["get project by id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id_or_slug}/projects/{project_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project by slug
         * @description Get a project by its slug.
         */
        get: operations["get project by slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/create_deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create deployment
         * @description Create a new deployment for a project.
         */
        post: operations["create deployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete deployment
         * @description Delete a deployment. This will delete all data and files in the deployment,
         *     so we recommend creating and downloading a backup before calling this
         *     endpoint. This does not delete the project itself.
         */
        post: operations["delete deployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get deployment
         * @description Get details about a cloud deployment.
         */
        get: operations["platform_get_deployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update deployment
         * @description Updates properties of an existing deployment. Only the fields provided in
         *     the request body are modified; omitted fields are left unchanged.
         */
        patch: operations["update deployment"];
        trace?: never;
    };
    "/teams/{team_id}/list_deployment_classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deployment classes
         * @description Lists the available deployment classes for a team.
         */
        get: operations["list deployment classes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/list_deployment_regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deployment regions
         * @description Lists the available deployment regions for a team.
         */
        get: operations["list deployment regions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/list_deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deployments for team
         * @description Lists deployments for a team with pagination, sorting, and filtering.
         */
        get: operations["list deployments for team"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/list_local_deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List local deployments
         * @description Lists the local deployments for a team.
         */
        get: operations["list local deployments for team"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/create_deploy_key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create deploy key
         * @description Create a deploy key like "dev:happy-animal-123|ey..." which can be
         *     used with the Convex CLI to develop against or deploy code.
         *
         *     When access to the deployment is granted through an OAuth token this
         *     deploy key will use the same OAuth-granted token.
         *
         *     When access to the deployment is granted any other way a new token will be
         *     created which grants access only to this deployment.
         */
        post: operations["create deploy key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/list_deploy_keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deploy keys
         * @description Lists all deploy keys for the specified deployment.
         */
        get: operations["list deploy keys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/delete_deploy_key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete deploy key
         * @description Deletes a deploy key for the specified deployment. The `id` in the request
         *     body can be the full deploy key (with prefix), encoded token, or the name of
         *     the deploy key.
         */
        post: operations["delete deploy key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/create_preview_deploy_key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create preview deploy key
         * @description Create a preview deploy key like "preview:team-slug:project-slug|ey..."
         *     which can be used with the Convex CLI to create and manage preview
         *     deployments within the project.
         */
        post: operations["create preview deploy key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/list_preview_deploy_keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List preview deploy keys
         * @description Lists all preview deploy keys for the specified project.
         */
        get: operations["list preview deploy keys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/delete_preview_deploy_key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete preview deploy key
         * @description Deletes a preview deploy key for the specified project. The `id` in the
         *     request body can be the full preview deploy key (with prefix), encoded
         *     token, or the name of the preview deploy key.
         */
        post: operations["delete preview deploy key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token_details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get token details
         * @description Returns the team ID for team tokens.
         *     Especially useful after receiving a team token from an OAuth flow
         *     since most endpoints require team ID.
         */
        get: operations["get token details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/create_custom_domain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create custom domain */
        post: operations["create custom domain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/delete_custom_domain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete custom domain
         * @description Remove a custom domain from a deployment.
         */
        post: operations["delete custom domain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/custom_domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List custom domains
         * @description Get all custom domains configured for a deployment.
         */
        get: operations["list custom domains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/list_members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List team members
         * @description List the members of the given team.
         */
        get: operations["list team members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/create_team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a team */
        post: operations["create team"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/create_access_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a team management access token */
        post: operations["create team management access token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Encrypted admin key */
        AdminKey: string;
        /** @enum {string} */
        CreateDeploymentType: "dev" | "prod" | "preview" | "custom";
        CreateTeamManagementAccessTokenResponse: {
            accessToken: string;
            tokenType: string;
        };
        /** @enum {string} */
        DeploymentClass: "s16" | "s256" | "d1024";
        DeploymentClassMetadata: {
            available: boolean;
            type: components["schemas"]["DeploymentClass"];
        };
        /** Format: int64 */
        DeploymentId: number;
        /** @description An identifier that uniquely identifies this deployment within the project. */
        DeploymentReference: string;
        DeploymentRegionMetadata: {
            available: boolean;
            displayName: string;
            name: components["schemas"]["RegionName"];
        };
        /** @enum {string} */
        DeploymentType: "dev" | "prod" | "preview" | "custom";
        DeviceName: string;
        /** @description Indicates whether the deployment is the default prod deployment for the
         *     project, or the default cloud dev deployment for the member in the project. */
        IsDefaultDeployment: boolean;
        ListDeploymentClassesResponse: {
            items: components["schemas"]["DeploymentClassMetadata"][];
        };
        ListDeploymentRegionsResponse: {
            items: components["schemas"]["DeploymentRegionMetadata"][];
        };
        ListLocalDeploymentsResponse: {
            items: components["schemas"]["PlatformDeploymentResponse"][];
        };
        ManagedBy: "vercel" | {
            oauthApp: string;
        };
        /** Format: int64 */
        MemberId: number;
        PaginatedDeploymentsResponse: {
            items: components["schemas"]["PlatformDeploymentResponse"][];
            pagination: components["schemas"]["PaginationMetadata"];
        };
        PaginationMetadata: {
            hasMore: boolean;
            nextCursor?: string | null;
        };
        PlatformCreateDeployKeyArgs: {
            /** @description Name for the deploy key. */
            name: string;
        };
        PlatformCreateDeployKeyResponse: {
            /** @description The generated deploy key. */
            deployKey: components["schemas"]["AdminKey"];
        };
        PlatformCreateDeploymentArgs: {
            /** @description The class to use for this deployment. If not provided, the default
             *     deployment class for your team will be used. */
            class?: string | null;
            /** @description An identifier that uniquely identifies this deployment within the
             *     project. By providing a reference, you can create multiple dev and prod
             *     deployments in the project. If you don’t provide a reference, the
             *     endpoint will create the default production deployment for the project,
             *     or the default development deployment for the member that creates it
             *     (i.e. the deployment used by default when running `npx convex deploy`
             *     or `npx convex dev` respectively). When not providing a reference,
             *     a reference will be automatically generated. */
            reference?: string | null;
            region?: null | components["schemas"]["RegionName"];
            type: components["schemas"]["CreateDeploymentType"];
        };
        PlatformCreatePreviewDeployKeyArgs: {
            /** @description Name for the preview deploy key. */
            name: string;
        };
        PlatformCreatePreviewDeployKeyResponse: {
            /** @description The generated preview deploy key. */
            previewDeployKey: components["schemas"]["AdminKey"];
        };
        PlatformCreateProjectArgs: {
            /** @description When creating a deployment, the class to use for the deployment.
             *     If not provided, the default deployment class for your team will be
             *     used. */
            deploymentClass?: string | null;
            deploymentRegion?: null | components["schemas"]["RegionName"];
            deploymentType?: null | components["schemas"]["CreateDeploymentType"];
            /** @description The full name of the project as it will appear in the dashboard. Spaces
             *     and punctuations allowed. */
            projectName: components["schemas"]["ProjectName"];
        };
        PlatformCreateProjectResponse: {
            /** @description The readable identifier for this deployment, something like
             *     playful-otter-123. Only present when a deployment was requested. */
            deploymentName?: string | null;
            /** @description Deployment cloud URL, where this deployment lives. Only present when a
             *     deployment was requested. */
            deploymentUrl?: string | null;
            projectId: components["schemas"]["ProjectId"];
        };
        PlatformCreateTeamArgs: {
            defaultRegion: components["schemas"]["RegionName"];
            name: components["schemas"]["ProposedTeamName"];
        };
        PlatformCustomDomainResponse: {
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this domain was created.
             */
            creationTime: number;
            /** @description The deployment name this domain is configured for. */
            deploymentName: string;
            /** @description The custom domain name. */
            domain: string;
            /** @description The destination for this custom domain (convexCloud or convexSite). */
            requestDestination: components["schemas"]["RequestDestination"];
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this domain was verified, or null if not
             *     yet verified.
             */
            verificationTime?: number | null;
        };
        PlatformDeleteCustomDomainArgs: {
            /** @description The custom domain name to delete. */
            domain: string;
            /** @description The destination for this custom domain (convexCloud or convexSite). */
            requestDestination: components["schemas"]["RequestDestination"];
        };
        PlatformDeleteDeployKeyArgs: {
            /** @description The token to delete. This can be the secret value of the token or the
             *     token's unique name. */
            id: string;
        };
        PlatformDeletePreviewDeployKeyArgs: {
            /** @description The token to delete. This can be the secret value of the token or the
             *     token's unique name. */
            id: string;
        };
        PlatformDeployKeyResponse: {
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this token was created.
             */
            creationTime: number;
            creator?: null | components["schemas"]["MemberId"];
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this token was last used (if ever).
             */
            lastUsedTime?: number | null;
            managedBy?: null | components["schemas"]["ManagedBy"];
            /** @description The name given to the deploy key at creation. */
            name: string;
        };
        PlatformDeploymentResponse: {
            /** @description The deployment class for this deployment. */
            class: string;
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this deployment was created.
             */
            createTime: number;
            creator?: null | components["schemas"]["MemberId"];
            /** @description Controls whether the dashboard requires a confirmation before
             *     allowing edits during a browser session for this deployment.
             *     If not set, defaults to true for prod deployments and false
             *     for dev and preview deployments. */
            dashboardEditConfirmation?: boolean | null;
            /** @description The type of this deployment. */
            deploymentType: components["schemas"]["DeploymentType"];
            /** @description The full backend URL for this deployment (e.g. "https://joyful-capybara-123.convex.cloud" or "https://calm-cow-456.eu-west-1.convex.cloud"). This is always a `.convex.cloud` URL, even when the deployment is using custom domains. To get the canonical URL, use [`/get_canonical_urls`](https://docs.convex.dev/deployment-api/get-canonical-urls). */
            deploymentUrl: string;
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this deployment will be
             *     deleted. Preview deployments have this set by default unless
             *     overridden.
             */
            expiresAt?: number | null;
            id: components["schemas"]["DeploymentId"];
            /** @description For prod deployments, whether they are the default prod deployment
             *     of the project. For dev deployments, whether they are the default
             *     dev deployment for the member that created it.
             *     For other deployments, set to false. */
            isDefault: components["schemas"]["IsDefaultDeployment"];
            /** @enum {string} */
            kind: "cloud";
            /**
             * Format: int64
             * @description Timestamp in milliseconds of the last deploy to this deployment, if
             *     any.
             */
            lastDeployTime?: number | null;
            /** @description The readable identifier for this deployment, something like
             *     playful-otter-123. */
            name: string;
            previewIdentifier?: null | components["schemas"]["PreviewDeploymentIdentifier"];
            /** @description The project this deployment belongs to. */
            projectId: components["schemas"]["ProjectId"];
            /** @description An identifier that uniquely identifies this deployment within the
             *     project. */
            reference: components["schemas"]["DeploymentReference"];
            /** @description The region where this deployment is hosted. */
            region: components["schemas"]["RegionName"];
            /** @description Whether to send function logs to the client. If `null`, the
             *     deployment-type default is used (true for dev/preview, false for
             *     prod). */
            sendLogsToClient?: boolean | null;
        } | {
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this deployment was created.
             */
            createTime: number;
            /** @description The member who created this deployment. */
            creator: components["schemas"]["MemberId"];
            /** @description Whether this is a "dev" development deployment or "prod" production
             *     deployment. Note that this will always be "dev" for local
             *     deployments. */
            deploymentType: components["schemas"]["DeploymentType"];
            /** @description The device name where this local deployment is running. */
            deviceName: components["schemas"]["DeviceName"];
            /** @description Whether this local deployment is currently active. */
            isActive: boolean;
            /** @enum {string} */
            kind: "local";
            /** @description The readable identifier for this deployment. */
            name: string;
            /**
             * Format: int32
             * @description The port where this local deployment is running.
             */
            port: number;
            previewIdentifier?: null | components["schemas"]["PreviewDeploymentIdentifier"];
            /** @description The project this deployment belongs to. */
            projectId: components["schemas"]["ProjectId"];
        };
        PlatformListCustomDomainsResponse: {
            /** @description List of custom domains configured for this deployment. */
            domains: components["schemas"]["PlatformCustomDomainResponse"][];
        };
        PlatformListPreviewDeployKeysResponse: {
            /** @description The list of preview deploy keys. */
            items: components["schemas"]["PlatformDeployKeyResponse"][];
        };
        PlatformListTeamMembersResponse: {
            items: components["schemas"]["TeamMember"][];
        };
        PlatformProjectDetails: {
            /**
             * Format: int64
             * @description Timestamp in milliseconds.
             */
            createTime: number;
            id: components["schemas"]["ProjectId"];
            /** @description The full project name, including spaces and punctuation. */
            name: components["schemas"]["ProjectName"];
            /** @description This shortened version of the name used in Convex Dashboard URLs. */
            slug: components["schemas"]["ProjectSlug"];
            teamId: components["schemas"]["TeamId"];
            /** @description The slug of the team that owns this project. */
            teamSlug: components["schemas"]["TeamSlug"];
        };
        PlatformTokenDetailsResponse: {
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this token was created.
             */
            createTime: number;
            /** @description The name given to the token at creation. */
            name: components["schemas"]["DeviceName"];
            /** @description The team ID this token is associated with. */
            teamId: components["schemas"]["TeamId"];
            /** @enum {string} */
            type: "teamToken";
        } | {
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this token was created.
             */
            createTime: number;
            /** @description The name given to the token at creation. */
            name: components["schemas"]["DeviceName"];
            /** @description The project ID this token is associated with. */
            projectId: components["schemas"]["ProjectId"];
            /** @enum {string} */
            type: "projectToken";
        };
        PlatformUpdateDeploymentArgs: {
            /** @description Controls whether the dashboard requires a confirmation before allowing
             *     edits during a browser session for this deployment. If set to `null`,
             *     the setting is reset to the default behavior (true for prod deployments,
             *     false for dev and preview deployments). If set to `true` or `false`, the
             *     setting is explicitly overridden. */
            dashboardEditConfirmation?: boolean | null;
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this deployment will be deleted.
             *     Preview deployments have this set by default unless overridden.
             *     Must be at least 30 minutes in the future and cannot exceed the
             *     team's preview deployment retention days entitlement from now.
             *     Set to `null` to clear the expiration.
             */
            expiresAt?: number | null;
            /** @description The reference of the deployment. When provided, must match the following
             *     rules:
             *       - be unique across deployment references in the project
             *       - 3 to 100 characters (included)
             *       - only lowercase letters, numbers, "-"" and "/"
             *       - not follow the deployment name format [a-z]+-[a-z]+-[0-9]+ (e.g.
             *         "happy-capybara-123")
             *       - not start with "local-""
             *       - not be one of the following reserved keywords: "prod", "dev",
             *         "cloud", "local", "default", "name", "new", "existing",
             *         "deployment", "preview" */
            reference?: string | null;
            /** @description Whether to send function logs to the client. If set to `null`, the
             *     setting is reset to the deployment-type default (true for dev/preview,
             *     false for prod). If set to `true` or `false`, the setting is explicitly
             *     overridden. */
            sendLogsToClient?: boolean | null;
        };
        PreviewDeploymentIdentifier: string;
        /** Format: int64 */
        ProjectId: number;
        ProjectName: string;
        ProjectSlug: string;
        ProposedTeamName: string;
        ReferralCode: string;
        /** @enum {string} */
        RegionName: "aws-us-east-1" | "aws-eu-west-1";
        /** @enum {string} */
        RequestDestination: "convexCloud" | "convexSite";
        /** @enum {string} */
        Role: "admin" | "developer";
        /** Format: int64 */
        TeamId: number;
        TeamMember: {
            /** @description The email of the team member */
            email: string;
            id: components["schemas"]["MemberId"];
            /** @description The name of the team member */
            name?: string | null;
            /** @description The role of the team member */
            role: components["schemas"]["Role"];
        };
        TeamName: string;
        TeamResponse: {
            creator?: null | components["schemas"]["MemberId"];
            defaultRegion?: null | components["schemas"]["RegionName"];
            id: components["schemas"]["TeamId"];
            managedBy?: null | components["schemas"]["ManagedBy"];
            managedByUrl?: string | null;
            name: components["schemas"]["TeamName"];
            referralCode: components["schemas"]["ReferralCode"];
            referredBy?: null | components["schemas"]["TeamId"];
            slug: components["schemas"]["TeamSlug"];
            ssoLoginId?: string | null;
            suspended: boolean;
        };
        TeamSlug: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AdminKey = components['schemas']['AdminKey'];
export type CreateDeploymentType = components['schemas']['CreateDeploymentType'];
export type CreateTeamManagementAccessTokenResponse = components['schemas']['CreateTeamManagementAccessTokenResponse'];
export type DeploymentClass = components['schemas']['DeploymentClass'];
export type DeploymentClassMetadata = components['schemas']['DeploymentClassMetadata'];
export type DeploymentId = components['schemas']['DeploymentId'];
export type DeploymentReference = components['schemas']['DeploymentReference'];
export type DeploymentRegionMetadata = components['schemas']['DeploymentRegionMetadata'];
export type DeploymentType = components['schemas']['DeploymentType'];
export type DeviceName = components['schemas']['DeviceName'];
export type IsDefaultDeployment = components['schemas']['IsDefaultDeployment'];
export type ListDeploymentClassesResponse = components['schemas']['ListDeploymentClassesResponse'];
export type ListDeploymentRegionsResponse = components['schemas']['ListDeploymentRegionsResponse'];
export type ListLocalDeploymentsResponse = components['schemas']['ListLocalDeploymentsResponse'];
export type ManagedBy = components['schemas']['ManagedBy'];
export type MemberId = components['schemas']['MemberId'];
export type PaginatedDeploymentsResponse = components['schemas']['PaginatedDeploymentsResponse'];
export type PaginationMetadata = components['schemas']['PaginationMetadata'];
export type PlatformCreateDeployKeyArgs = components['schemas']['PlatformCreateDeployKeyArgs'];
export type PlatformCreateDeployKeyResponse = components['schemas']['PlatformCreateDeployKeyResponse'];
export type PlatformCreateDeploymentArgs = components['schemas']['PlatformCreateDeploymentArgs'];
export type PlatformCreatePreviewDeployKeyArgs = components['schemas']['PlatformCreatePreviewDeployKeyArgs'];
export type PlatformCreatePreviewDeployKeyResponse = components['schemas']['PlatformCreatePreviewDeployKeyResponse'];
export type PlatformCreateProjectArgs = components['schemas']['PlatformCreateProjectArgs'];
export type PlatformCreateProjectResponse = components['schemas']['PlatformCreateProjectResponse'];
export type PlatformCreateTeamArgs = components['schemas']['PlatformCreateTeamArgs'];
export type PlatformCustomDomainResponse = components['schemas']['PlatformCustomDomainResponse'];
export type PlatformDeleteCustomDomainArgs = components['schemas']['PlatformDeleteCustomDomainArgs'];
export type PlatformDeleteDeployKeyArgs = components['schemas']['PlatformDeleteDeployKeyArgs'];
export type PlatformDeletePreviewDeployKeyArgs = components['schemas']['PlatformDeletePreviewDeployKeyArgs'];
export type PlatformDeployKeyResponse = components['schemas']['PlatformDeployKeyResponse'];
export type PlatformDeploymentResponse = components['schemas']['PlatformDeploymentResponse'];
export type PlatformListCustomDomainsResponse = components['schemas']['PlatformListCustomDomainsResponse'];
export type PlatformListPreviewDeployKeysResponse = components['schemas']['PlatformListPreviewDeployKeysResponse'];
export type PlatformListTeamMembersResponse = components['schemas']['PlatformListTeamMembersResponse'];
export type PlatformProjectDetails = components['schemas']['PlatformProjectDetails'];
export type PlatformTokenDetailsResponse = components['schemas']['PlatformTokenDetailsResponse'];
export type PlatformUpdateDeploymentArgs = components['schemas']['PlatformUpdateDeploymentArgs'];
export type PreviewDeploymentIdentifier = components['schemas']['PreviewDeploymentIdentifier'];
export type ProjectId = components['schemas']['ProjectId'];
export type ProjectName = components['schemas']['ProjectName'];
export type ProjectSlug = components['schemas']['ProjectSlug'];
export type ProposedTeamName = components['schemas']['ProposedTeamName'];
export type ReferralCode = components['schemas']['ReferralCode'];
export type RegionName = components['schemas']['RegionName'];
export type RequestDestination = components['schemas']['RequestDestination'];
export type Role = components['schemas']['Role'];
export type TeamId = components['schemas']['TeamId'];
export type TeamMember = components['schemas']['TeamMember'];
export type TeamName = components['schemas']['TeamName'];
export type TeamResponse = components['schemas']['TeamResponse'];
export type TeamSlug = components['schemas']['TeamSlug'];
export type $defs = Record<string, never>;
export interface operations {
    "create project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID */
                team_id: components["schemas"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformCreateProjectArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformCreateProjectResponse"];
                };
            };
        };
    };
    "list projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID */
                team_id: components["schemas"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProjectDetails"][];
                };
            };
        };
    };
    "list deployments": {
        parameters: {
            query?: {
                /** @description If true, include local deployments in the response (filtered to only
                 *     show local deployments created by the requesting team member). */
                includeLocal?: boolean;
                /** @description If true, only include default deployments. If false, only include
                 *     non-default deployments. */
                isDefault?: boolean | null;
                /** @description Only include deployments of the given deployment type. */
                deploymentType?: null | components["schemas"]["DeploymentType"];
            };
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDeploymentResponse"][];
                };
            };
        };
    };
    "get deployment in project by project id": {
        parameters: {
            query?: {
                /** @description The reference of the deployment to retrieve. */
                reference?: null | components["schemas"]["DeploymentReference"];
                /** @description If true, retrieve the default production deployment. */
                defaultProd?: boolean | null;
                /** @description If true, retrieve the default dev deployment for the calling user. */
                defaultDev?: boolean | null;
            };
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDeploymentResponse"];
                };
            };
        };
    };
    "get deployment in project by project slug": {
        parameters: {
            query?: {
                /** @description The reference of the deployment to retrieve. */
                reference?: null | components["schemas"]["DeploymentReference"];
                /** @description If true, retrieve the default production deployment. */
                defaultProd?: boolean | null;
                /** @description If true, retrieve the default dev deployment for the calling user. */
                defaultDev?: boolean | null;
            };
            header?: never;
            path: {
                /** @description Team ID or slug */
                team_id_or_slug: string;
                /** @description Project slug */
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDeploymentResponse"];
                };
            };
        };
    };
    "delete project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "get project by id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProjectDetails"];
                };
            };
        };
    };
    "get project by slug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID or slug */
                team_id_or_slug: string;
                /** @description Project slug */
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProjectDetails"];
                };
            };
        };
    };
    "create deployment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformCreateDeploymentArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDeploymentResponse"];
                };
            };
        };
    };
    "delete deployment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment Name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    platform_get_deployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment Name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDeploymentResponse"];
                };
            };
        };
    };
    "update deployment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment Name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformUpdateDeploymentArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "list deployment classes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDeploymentClassesResponse"];
                };
            };
        };
    };
    "list deployment regions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDeploymentRegionsResponse"];
                };
            };
        };
    };
    "list deployments for team": {
        parameters: {
            query?: {
                /** @description Cursor for pagination */
                cursor?: string;
                /** @description Max results per page (default: 100, max: 100) */
                limit?: number;
                /** @description Sort field: createTime, lastDeployTime, reference */
                sort_by?: string;
                /** @description Sort order: asc, desc */
                sort_order?: string;
                /** @description Filter by type: dev, prod, preview, custom */
                deployment_type?: string;
                /** @description Search by deployment name or reference */
                q?: string;
                /** @description Filter by project ID */
                project_id?: components["schemas"]["ProjectId"];
                /** @description Filter by creator member ID */
                creator?: components["schemas"]["MemberId"];
                /** @description Filter by default deployment status */
                is_default?: boolean;
            };
            header?: never;
            path: {
                /** @description Team ID */
                team_id: components["schemas"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDeploymentsResponse"];
                };
            };
        };
    };
    "list local deployments for team": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID */
                team_id: components["schemas"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListLocalDeploymentsResponse"];
                };
            };
        };
    };
    "create deploy key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformCreateDeployKeyArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformCreateDeployKeyResponse"];
                };
            };
        };
    };
    "list deploy keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDeployKeyResponse"][];
                };
            };
        };
    };
    "delete deploy key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformDeleteDeployKeyArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "create preview deploy key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformCreatePreviewDeployKeyArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformCreatePreviewDeployKeyResponse"];
                };
            };
        };
    };
    "list preview deploy keys": {
        parameters: {
            query?: {
                /** @description If true, include managed preview deploy keys (e.g., created by external
                 *     integrations like Vercel) in the response. Defaults to false. */
                includeManaged?: boolean;
            };
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformListPreviewDeployKeysResponse"];
                };
            };
        };
    };
    "delete preview deploy key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformDeletePreviewDeployKeyArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "get token details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformTokenDetailsResponse"];
                };
            };
        };
    };
    "create custom domain": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformDeleteCustomDomainArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "delete custom domain": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformDeleteCustomDomainArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "list custom domains": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformListCustomDomainsResponse"];
                };
            };
        };
    };
    "list team members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID */
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformListTeamMembersResponse"];
                };
            };
        };
    };
    "create team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformCreateTeamArgs"];
            };
        };
        responses: {
            /** @description Team created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Caller is not authorized to create teams */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "create team management access token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team management access token created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTeamManagementAccessTokenResponse"];
                };
            };
            /** @description Caller is not authorized to create team management access tokens */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
