/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/update_environment_variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update environment variables
         * @description Update one or many environment variables in a deployment.
         *     This will invalidate all subscriptions, since environment variables
         *     are accessible in queries but are not part of the cache key of a query
         *     result.
         */
        post: operations["update_environment_variables"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list_environment_variables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List environment variables
         * @description Get all environment variables in a deployment.
         *     In the future this might not include "secret" environment
         *     variables.
         */
        get: operations["list_environment_variables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list_audit_log_events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit log events
         * @description List a deployment's audit log events on or after a timestamp, from least to
         *     most recent. Pass the returned `cursor` (along with the same `from`) to
         *     fetch the next page.
         */
        get: operations["list_audit_log_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployment_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get deployment info
         * @description Returns identity information about this deployment.
         */
        get: operations["get deployment info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list_usage_limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List usage limits
         * @description Get all usage limit configs for a deployment.
         */
        get: operations["list_usage_limits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_usage_limit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create usage limit
         * @description Create a new usage limit config for a deployment.
         */
        post: operations["create_usage_limit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update_usage_limit/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update usage limit
         * @description Replace an existing usage limit config for a deployment.
         */
        post: operations["update_usage_limit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete_usage_limit/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete usage limit
         * @description Delete an existing usage limit config for a deployment.
         */
        post: operations["delete_usage_limit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update_canonical_url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update canonical URL
         * @description Set or unset the canonical URL for a deployment's convex.cloud or
         *     convex.site domain. This allows you to customize the  CONVEX_SITE_URL and
         *     CONVEX_CLOUD_URL environment variables in your deployment.
         */
        post: operations["update_canonical_url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_canonical_urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get canonical URLs
         * @description Get the canonical URLs for a deployment.
         */
        get: operations["get_canonical_urls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list_log_streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List log streams
         * @description List configs for all existing log streams in a deployment.
         */
        get: operations["list_log_streams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/get_log_stream/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get log stream
         * @description Get the config for a specific log stream by id.
         */
        get: operations["get_log_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete_log_stream/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete log stream
         * @description Delete the deployment's log stream with the given id.
         */
        post: operations["delete_log_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_log_stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create log stream
         * @description Create a new log stream for the deployment. Errors if a log stream of the
         *     given type already exists.
         */
        post: operations["create_log_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update_log_stream/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update log stream
         * @description Update an existing log stream for the deployment. Omit a field to keep the
         *     existing value, and use `null` to unset a field.
         */
        post: operations["update_log_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rotate_webhook_secret/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate webhook log stream secret
         * @description Rotate the secret for the webhook log stream.
         */
        post: operations["rotate_webhook_secret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pause_deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause deployment
         * @description Disables a deployment without deleting any data. The deployment will not
         *     operate until it is unpaused. While a deployment is paused, new functions
         *     calls will return an error, scheduled jobs will queue and run when the
         *     deployment is resumed, and cron jobs will be skipped. This means that no
         *     function calls or bandwidth usage will be charged while the deployment is
         *     paused, but storage costs will still apply.
         */
        post: operations["pause_deployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unpause_deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unpause deployment
         * @description Reenables a deployment that was previously paused. The deployment will
         *     resume normal operation, including any scheduled jobs that were queued while
         *     paused.
         */
        post: operations["unpause_deployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Data sync
         * @description **Early access:** this API is not yet stable and may change in
         *     backwards-incompatible ways without notice. Contact the Convex team before
         *     depending on it.
         *
         *     Streams a consistent, resumable export of a deployment's data — either the
         *     whole deployment or a subset of components, tables, and columns (see the
         *     request body). Streaming export must be enabled on the deployment.
         *
         *     Call this endpoint repeatedly, passing the `cursor` from each response back
         *     in the next request; omit `cursor` on the first call. The cursor is opaque —
         *     store and send it back verbatim. Each response contains:
         *
         *     - `values`: document revisions in the order they should be applied. A value
         *       with `_deleted: true` is a tombstone marking that document as deleted.
         *     - `truncates`: tables whose contents were replaced wholesale (for example by
         *       an `npx convex import`). Drop everything you have stored for each listed
         *       table; the `values` in this and later responses re-populate it.
         *     - `status`: `inProgress` while the export is still being assembled — the
         *       data returned so far is not yet a consistent view, so keep calling. Once
         *       it becomes `synced`, the values applied so far form a consistent snapshot
         *       of the deployment as of the returned `snapshot` timestamp. You can keep
         *       calling to continue streaming later changes; `hasMore` tells you whether
         *       more data is already available (`true`) or you've caught up to the latest
         *       commit (`false`).
         *
         *     Persist the cursor and keep calling within the deployment's data retention
         *     window so the export can resume where it left off. This endpoint must be
         *     called at least once every 3 days; if too much time passes between calls the
         *     cursor falls outside the retention window and can no longer be resumed. When
         *     that happens the endpoint responds with a `400` (`DataSyncCursorExpired`),
         *     and you must restart the sync from scratch by calling again with no cursor.
         */
        post: operations["data_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: int64 */
        AccessTokenId: number;
        /** @description The identity that performed an audit log action. */
        AuditLogActor: {
            /** @enum {string} */
            kind: "system";
        } | {
            /** @enum {string} */
            kind: "member";
            /** @description Member ID */
            member_id: components["schemas"]["MemberId"];
        } | {
            /** @description Client ID of the OAuth application, if the token belongs to one. */
            client_id?: string | null;
            /** @enum {string} */
            kind: "token";
            member_id?: null | components["schemas"]["MemberId"];
            /** @description Token ID. `0` for legacy audit log rows created before token IDs
             *     were recorded. */
            token_id: components["schemas"]["AccessTokenId"];
        };
        AxiomAttribute: {
            key: string;
            value: string;
        };
        /** AxiomConfig */
        AxiomLogStreamConfig: {
            /** @description Optional list of attributes. These are extra fields and values sent to
             *     Axiom in each log event. */
            attributes: components["schemas"]["AxiomAttribute"][];
            /** @description Name of the dataset in Axiom. This is where the logs will be sent. */
            datasetName: string;
            id: string;
            /** @description Optional ingest endpoint for Axiom */
            ingestUrl?: string | null;
            /** @description Status of the log stream */
            status: components["schemas"]["LogStreamStatus"];
            /** @description The topics this log stream is subscribed to. `null` means subscribed to
             *     all topics, including ones added in the future. */
            topics?: components["schemas"]["LogTopic"][] | null;
        };
        CreateAxiomLogStreamArgs: {
            /** @description Axiom API key for authentication. */
            apiKey: string;
            /** @description Optional list of attributes. These are extra fields and values sent to
             *     Axiom in each log event. */
            attributes: components["schemas"]["AxiomAttribute"][];
            /** @description Name of the dataset in Axiom. This is where the logs will be sent. */
            datasetName: string;
            /** @description Optional ingest endpoint for Axiom */
            ingestUrl?: string | null;
            /** @description The topics this log stream is subscribed to. Omit to
             *     subscribe to all topics, including ones added in the future. */
            topics?: components["schemas"]["LogTopic"][] | null;
        };
        CreateDatadogLogStreamArgs: {
            /** @description Datadog API key for authentication. */
            ddApiKey: string;
            /** @description Optional comma-separated list of tags. These are sent to Datadog in each
             *     log event via the `ddtags` field. */
            ddTags: string[];
            /** @description Service name used as a special tag in Datadog. */
            service?: string | null;
            /** @description Location of your Datadog deployment. */
            siteLocation: components["schemas"]["DatadogSiteLocation"];
            /** @description The topics this log stream is subscribed to. Omit to
             *     subscribe to all topics, including ones added in the future. */
            topics?: components["schemas"]["LogTopic"][] | null;
        };
        CreateLogStreamArgs: (components["schemas"]["CreateDatadogLogStreamArgs"] & {
            /** @enum {string} */
            logStreamType: "datadog";
        }) | (components["schemas"]["CreateWebhookLogStreamArgs"] & {
            /** @enum {string} */
            logStreamType: "webhook";
        }) | (components["schemas"]["CreateAxiomLogStreamArgs"] & {
            /** @enum {string} */
            logStreamType: "axiom";
        }) | (components["schemas"]["CreateSentryLogStreamArgs"] & {
            /** @enum {string} */
            logStreamType: "sentry";
        }) | (components["schemas"]["CreatePostHogLogsLogStreamArgs"] & {
            /** @enum {string} */
            logStreamType: "postHogLogs";
        }) | (components["schemas"]["CreatePostHogErrorTrackingLogStreamArgs"] & {
            /** @enum {string} */
            logStreamType: "postHogErrorTracking";
        });
        CreateLogStreamResponse: (components["schemas"]["CreateWebhookLogStreamResponse"] & {
            /** @enum {string} */
            logStreamType: "webhook";
        }) | {
            id: string;
            /** @enum {string} */
            logStreamType: "datadog";
        } | {
            id: string;
            /** @enum {string} */
            logStreamType: "axiom";
        } | {
            id: string;
            /** @enum {string} */
            logStreamType: "sentry";
        } | {
            id: string;
            /** @enum {string} */
            logStreamType: "postHogLogs";
        } | {
            id: string;
            /** @enum {string} */
            logStreamType: "postHogErrorTracking";
        };
        CreatePostHogErrorTrackingLogStreamArgs: {
            /** @description PostHog project token. */
            apiKey: string;
            /** @description PostHog host URL. Defaults to https://us.i.posthog.com. */
            host?: string | null;
        };
        CreatePostHogLogsLogStreamArgs: {
            /** @description PostHog project token. */
            apiKey: string;
            /** @description PostHog host URL. Defaults to https://us.i.posthog.com. */
            host?: string | null;
            /** @description OTLP service.name attribute. Defaults to the deployment name. */
            serviceName?: string | null;
            /** @description The topics this log stream is subscribed to. Omit to
             *     subscribe to all topics, including ones added in the future. */
            topics?: components["schemas"]["LogTopic"][] | null;
        };
        CreateSentryLogStreamArgs: {
            /** @description Sentry Data Source Name (DSN) to route exceptions to. */
            dsn: string;
            /** @description Tags to add to all events routed to Sentry. */
            tags?: {
                [key: string]: string;
            } | null;
        };
        CreateWebhookLogStreamArgs: {
            /** @description Format for the webhook payload. JSONL sends one object per line of
             *     request, JSON sends one array per request. */
            format: components["schemas"]["WebhookFormat"];
            /** @description The topics this log stream is subscribed to. Omit to
             *     subscribe to all topics, including ones added in the future. */
            topics?: components["schemas"]["LogTopic"][] | null;
            /** @description URL to send logs to. */
            url: string;
        };
        CreateWebhookLogStreamResponse: {
            /** @description Use this secret to verify webhook signatures. */
            hmacSecret: string;
            id: string;
        };
        /** @description Arguments to the data sync (streaming export) API (`/api/v1/data/sync`). */
        DataSyncArgs: Record<string, never> & {
            /** @description Opaque cursor returned by a previous call. Omit to start from scratch. */
            cursor?: string | null;
        };
        /** @description Progress indicator returned while a data sync is `InProgress`. */
        DataSyncProgress: {
            currentComponent?: string | null;
            currentTable?: string | null;
            /** Format: int64 */
            numDocumentsInCurrentTable: number;
            /** Format: int64 */
            numTablesSynced: number;
            /** Format: int64 */
            totalTables: number;
        };
        /** @description One page returned by the data sync API. */
        DataSyncResponse: {
            /** @description Opaque cursor to pass back in as `cursor` on the next call. */
            cursor: string;
            /** @description The consistency state of the sync after this page. */
            status: components["schemas"]["DataSyncStatus"];
            /** @description Tables truncated by this page: the consumer should drop everything it
             *     previously synced for each, then apply `values` (which re-sync them from
             *     scratch). Logically applies before `values`. */
            truncates: components["schemas"]["DataSyncTruncate"][];
            /** @description Documents and tombstones produced by this page. */
            values: components["schemas"]["DataSyncValue"][];
        };
        /** @description The consistency state reported alongside a data sync page. */
        DataSyncStatus: {
            /** @description Whether `snapshot` is behind the latest timestamp — i.e. it's a
             *     consistent snapshot but not fully caught up to the most recent
             *     commit. Callers use this to decide whether to keep calling the API
             *     or pause until later. */
            hasMore: boolean;
            /** Format: int64 */
            snapshot: number;
            /** @enum {string} */
            type: "synced";
        } | (components["schemas"]["DataSyncProgress"] & {
            /** @enum {string} */
            type: "inProgress";
        });
        /** @description A table whose contents were replaced wholesale (e.g. by `npx convex
         *     import`). Reported separately from `values` since it carries none of the
         *     per-document fields. */
        DataSyncTruncate: {
            /** @description The path of the component the table is in. */
            _component: string;
            /** @description The name of the truncated table. */
            _table: string;
        };
        /** @description A single document-level entry emitted by the data sync API: a Convex
         *     document (or a tombstone, for a deletion) with some special fields added. */
        DataSyncValue: Record<string, never> & {
            /** @description The path of the component this entry is from. */
            _component: string;
            /** @description Whether the document was deleted (a tombstone). */
            _deleted: boolean;
            /** @description The name of the table this entry is from. */
            _table: string;
            /**
             * Format: int64
             * @description The timestamp at which this revision was written.
             */
            _ts: number;
        };
        /** DatadogConfig */
        DatadogLogStreamConfig: {
            /** @description Optional comma-separated list of tags. These are sent to Datadog in each
             *     log event via the `ddtags` field. */
            ddTags: string[];
            id: string;
            /** @description Service name used as a special tag in Datadog. */
            service?: string | null;
            /** @description Location of your Datadog deployment. */
            siteLocation: components["schemas"]["DatadogSiteLocation"];
            /** @description Status of the log stream */
            status: components["schemas"]["LogStreamStatus"];
            /** @description The topics this log stream is subscribed to. `null` means subscribed to
             *     all topics, including ones added in the future. */
            topics?: components["schemas"]["LogTopic"][] | null;
        };
        /**
         * @description The Datadog deployment locations, used to construct URLs
         * @enum {string}
         */
        DatadogSiteLocation: "US1" | "US3" | "US5" | "EU" | "US1_FED" | "AP1";
        DeploymentAuditLogEventResponse: {
            /** @enum {string} */
            action: "create_environment_variable" | "update_environment_variable" | "delete_environment_variable" | "create_usage_limit" | "update_usage_limit" | "delete_usage_limit" | "usage_limit_exceeded" | "replace_environment_variable" | "update_canonical_url" | "delete_canonical_url" | "push_config" | "push_config_with_components" | "build_indexes" | "change_deployment_state" | "pause_deployment" | "unpause_deployment" | "change_system_stop_state" | "clear_tables" | "snapshot_import" | "delete_scheduled_jobs_table" | "delete_tables" | "delete_component" | "cancel_all_scheduled_functions" | "cancel_scheduled_function" | "request_export" | "cancel_export" | "set_export_expiration" | "create_integration" | "update_integration" | "delete_integration" | "add_documents" | "delete_documents" | "update_documents" | "create_table" | "delete_files" | "generate_upload_url";
            /** @description The identity that performed the action. */
            actor: components["schemas"]["AuditLogActor"];
            /** @description IP address of the client that performed the action, if known. */
            clientIp?: string | null;
            /** @description User agent of the client that performed the action, if known. */
            clientUserAgent?: string | null;
            /**
             * Format: int64
             * @description Time the event was created, in milliseconds since epoch.
             */
            createTime: number;
            /** @description Additional JSON metadata about the audit log event. */
            metadata: components["schemas"]["Value"];
        };
        /** Format: int64 */
        DeploymentId: number;
        DeploymentInfoResponse: {
            deploymentType: components["schemas"]["DeploymentType"];
            id: components["schemas"]["DeploymentId"];
            /** @enum {string} */
            kind: "cloud";
            projectId: components["schemas"]["ProjectId"];
            projectName?: string | null;
            projectSlug?: string | null;
            reference?: string | null;
            teamId: components["schemas"]["TeamId"];
        } | {
            /** @enum {string} */
            kind: "selfHosted";
        };
        /** @enum {string} */
        DeploymentType: "dev" | "prod" | "preview" | "custom";
        GetCanonicalUrlsResponse: {
            convexCloudUrl: string;
            convexSiteUrl: string;
        };
        ListDeploymentAuditLogEventsResponse: {
            /** @description The audit log events for this page, from least to most recent. */
            items: components["schemas"]["DeploymentAuditLogEventResponse"][];
            pagination: components["schemas"]["PaginationMetadata"];
        };
        ListEnvVarsResponse: {
            environmentVariables: {
                [key: string]: string;
            };
        };
        ListUsageLimitsResponse: {
            usageLimits: components["schemas"]["UsageLimitConfigResponse"][];
        };
        LogStreamConfig: (components["schemas"]["DatadogLogStreamConfig"] & {
            /** @enum {string} */
            logStreamType: "datadog";
        }) | (components["schemas"]["WebhookLogStreamConfig"] & {
            /** @enum {string} */
            logStreamType: "webhook";
        }) | (components["schemas"]["AxiomLogStreamConfig"] & {
            /** @enum {string} */
            logStreamType: "axiom";
        }) | (components["schemas"]["SentryLogStreamConfig"] & {
            /** @enum {string} */
            logStreamType: "sentry";
        }) | (components["schemas"]["PostHogLogsLogStreamConfig"] & {
            /** @enum {string} */
            logStreamType: "postHogLogs";
        }) | (components["schemas"]["PostHogErrorTrackingLogStreamConfig"] & {
            /** @enum {string} */
            logStreamType: "postHogErrorTracking";
        });
        /** @description Status of a log stream */
        LogStreamStatus: {
            /** @enum {string} */
            type: "pending";
        } | {
            /** @enum {string} */
            type: "restarting";
        } | {
            reason: string;
            /** @enum {string} */
            type: "failed";
        } | {
            /** @enum {string} */
            type: "active";
        } | {
            /** @enum {string} */
            type: "deleting";
        };
        /** @enum {string} */
        LogTopic: "verification" | "console" | "function_execution" | "exception" | "audit_log" | "scheduler_stats" | "scheduled_job_lag" | "current_storage_usage" | "concurrency_stats" | "storage_api_bandwidth" | "log_stream_egress" | "custom_audit";
        /** Format: int64 */
        MemberId: number;
        PaginationMetadata: {
            hasMore: boolean;
            nextCursor?: string | null;
        };
        /** PostHogErrorTrackingConfig */
        PostHogErrorTrackingLogStreamConfig: {
            /** @description PostHog host URL. */
            host?: string | null;
            id: string;
            /** @description Status of the log stream */
            status: components["schemas"]["LogStreamStatus"];
        };
        /** PostHogLogsConfig */
        PostHogLogsLogStreamConfig: {
            /** @description PostHog host URL. */
            host?: string | null;
            id: string;
            /** @description OTLP service.name attribute. */
            serviceName?: string | null;
            /** @description Status of the log stream */
            status: components["schemas"]["LogStreamStatus"];
            /** @description The topics this log stream is subscribed to. `null` means subscribed to
             *     all topics, including ones added in the future. */
            topics?: components["schemas"]["LogTopic"][] | null;
        };
        /** Format: int64 */
        ProjectId: number;
        /** @enum {string} */
        RequestDestination: "convexCloud" | "convexSite";
        RotateLogStreamSecretResponse: {
            hmacSecret: string;
            /** @enum {string} */
            logStreamType: "webhook";
        };
        /** SentryConfig */
        SentryLogStreamConfig: {
            id: string;
            /** @description Status of the log stream */
            status: components["schemas"]["LogStreamStatus"];
            /** @description Tags to add to all events routed to Sentry. */
            tags?: {
                [key: string]: string;
            } | null;
        };
        /** Format: int64 */
        TeamId: number;
        UpdateAxiomSinkArgs: {
            /** @description Axiom API key for authentication. */
            apiKey?: string | null;
            /** @description Optional list of attributes. These are extra fields and values sent to
             *     Axiom in each log event. */
            attributes?: components["schemas"]["AxiomAttribute"][] | null;
            /** @description Name of the dataset in Axiom. This is where the logs will be sent. */
            datasetName?: string | null;
            /** @description Optional ingest endpoint for Axiom */
            ingestUrl?: string | null;
            /** @description The topics this log stream is subscribed to. Omit to keep the current
             *     subscription, or pass `null` to subscribe to all topics (including ones
             *     added in the future). */
            topics?: components["schemas"]["LogTopic"][] | null;
        };
        UpdateCanonicalUrlRequest: {
            /** @description Whether to update the canonical URL for convex.cloud or convex.site */
            requestDestination: components["schemas"]["RequestDestination"];
            /** @description The new canonical URL. Omit this to reset the canonical URl to the
             *     default value. */
            url?: string | null;
        };
        UpdateDatadogSinkArgs: {
            /** @description Datadog API key for authentication. */
            ddApiKey?: string | null;
            /** @description Optional comma-separated list of tags. These are sent to Datadog in each
             *     log event via the `ddtags` field. */
            ddTags?: string[] | null;
            /** @description Service name used as a special tag in Datadog. */
            service?: string | null;
            siteLocation?: null | components["schemas"]["DatadogSiteLocation"];
            /** @description The topics this log stream is subscribed to. Omit to keep the current
             *     subscription, or pass `null` to subscribe to all topics (including ones
             *     added in the future). */
            topics?: components["schemas"]["LogTopic"][] | null;
        };
        UpdateEnvVarRequest: {
            name: string;
            value?: string | null;
        };
        UpdateEnvVarsRequest: {
            changes: components["schemas"]["UpdateEnvVarRequest"][];
        };
        UpdateLogStreamArgs: (components["schemas"]["UpdateDatadogSinkArgs"] & {
            /** @enum {string} */
            logStreamType: "datadog";
        }) | (components["schemas"]["UpdateWebhookSinkArgs"] & {
            /** @enum {string} */
            logStreamType: "webhook";
        }) | (components["schemas"]["UpdateAxiomSinkArgs"] & {
            /** @enum {string} */
            logStreamType: "axiom";
        }) | (components["schemas"]["UpdateSentrySinkArgs"] & {
            /** @enum {string} */
            logStreamType: "sentry";
        }) | (components["schemas"]["UpdatePostHogLogsSinkArgs"] & {
            /** @enum {string} */
            logStreamType: "postHogLogs";
        }) | (components["schemas"]["UpdatePostHogErrorTrackingSinkArgs"] & {
            /** @enum {string} */
            logStreamType: "postHogErrorTracking";
        });
        UpdatePostHogErrorTrackingSinkArgs: {
            /** @description PostHog project token. */
            apiKey?: string | null;
            /** @description PostHog host URL. */
            host?: string | null;
        };
        UpdatePostHogLogsSinkArgs: {
            /** @description PostHog project token. */
            apiKey?: string | null;
            /** @description PostHog host URL. */
            host?: string | null;
            /** @description OTLP service.name attribute. */
            serviceName?: string | null;
            /** @description The topics this log stream is subscribed to. Omit to keep the current
             *     subscription, or pass `null` to subscribe to all topics (including ones
             *     added in the future). */
            topics?: components["schemas"]["LogTopic"][] | null;
        };
        UpdateSentrySinkArgs: {
            /** @description Sentry Data Source Name (DSN) to route exceptions to. */
            dsn?: string | null;
            /** @description Tags to add to all events routed to Sentry. */
            tags?: {
                [key: string]: string;
            } | null;
        };
        UpdateWebhookSinkArgs: {
            format?: null | components["schemas"]["WebhookFormat"];
            /** @description The topics this log stream is subscribed to. Omit to keep the current
             *     subscription, or pass `null` to subscribe to all topics (including ones
             *     added in the future). */
            topics?: components["schemas"]["LogTopic"][] | null;
            /** @description URL to send logs to. */
            url?: string | null;
        };
        UsageLimitConfigRequest: {
            enabled: boolean;
            /** Format: int64 */
            limit: number;
            limitType: string;
            metric: string;
            name?: string | null;
            window: string;
        };
        UsageLimitConfigResponse: {
            enabled: boolean;
            id: string;
            /** Format: int64 */
            limit: number;
            limitType: string;
            metric: string;
            name?: string | null;
            window: string;
        };
        UsageLimitResponse: {
            usageLimit: components["schemas"]["UsageLimitConfigResponse"];
        };
        Value: unknown;
        /** @enum {string} */
        WebhookFormat: "json" | "jsonl";
        /** WebhookConfig */
        WebhookLogStreamConfig: {
            /** @description Format for the webhook payload. JSONL sends one object per line of
             *     request, JSON sends one array per request. */
            format: components["schemas"]["WebhookFormat"];
            /** @description Use this secret to verify webhook signatures. */
            hmacSecret: string;
            id: string;
            /** @description Status of the log stream */
            status: components["schemas"]["LogStreamStatus"];
            /** @description The topics this log stream is subscribed to. `null` means subscribed to
             *     all topics, including ones added in the future. */
            topics?: components["schemas"]["LogTopic"][] | null;
            /** @description URL to send logs to. */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AccessTokenId = components['schemas']['AccessTokenId'];
export type AuditLogActor = components['schemas']['AuditLogActor'];
export type AxiomAttribute = components['schemas']['AxiomAttribute'];
export type AxiomLogStreamConfig = components['schemas']['AxiomLogStreamConfig'];
export type CreateAxiomLogStreamArgs = components['schemas']['CreateAxiomLogStreamArgs'];
export type CreateDatadogLogStreamArgs = components['schemas']['CreateDatadogLogStreamArgs'];
export type CreateLogStreamArgs = components['schemas']['CreateLogStreamArgs'];
export type CreateLogStreamResponse = components['schemas']['CreateLogStreamResponse'];
export type CreatePostHogErrorTrackingLogStreamArgs = components['schemas']['CreatePostHogErrorTrackingLogStreamArgs'];
export type CreatePostHogLogsLogStreamArgs = components['schemas']['CreatePostHogLogsLogStreamArgs'];
export type CreateSentryLogStreamArgs = components['schemas']['CreateSentryLogStreamArgs'];
export type CreateWebhookLogStreamArgs = components['schemas']['CreateWebhookLogStreamArgs'];
export type CreateWebhookLogStreamResponse = components['schemas']['CreateWebhookLogStreamResponse'];
export type DataSyncArgs = components['schemas']['DataSyncArgs'];
export type DataSyncProgress = components['schemas']['DataSyncProgress'];
export type DataSyncResponse = components['schemas']['DataSyncResponse'];
export type DataSyncStatus = components['schemas']['DataSyncStatus'];
export type DataSyncTruncate = components['schemas']['DataSyncTruncate'];
export type DataSyncValue = components['schemas']['DataSyncValue'];
export type DatadogLogStreamConfig = components['schemas']['DatadogLogStreamConfig'];
export type DatadogSiteLocation = components['schemas']['DatadogSiteLocation'];
export type DeploymentAuditLogEventResponse = components['schemas']['DeploymentAuditLogEventResponse'];
export type DeploymentId = components['schemas']['DeploymentId'];
export type DeploymentInfoResponse = components['schemas']['DeploymentInfoResponse'];
export type DeploymentType = components['schemas']['DeploymentType'];
export type GetCanonicalUrlsResponse = components['schemas']['GetCanonicalUrlsResponse'];
export type ListDeploymentAuditLogEventsResponse = components['schemas']['ListDeploymentAuditLogEventsResponse'];
export type ListEnvVarsResponse = components['schemas']['ListEnvVarsResponse'];
export type ListUsageLimitsResponse = components['schemas']['ListUsageLimitsResponse'];
export type LogStreamConfig = components['schemas']['LogStreamConfig'];
export type LogStreamStatus = components['schemas']['LogStreamStatus'];
export type LogTopic = components['schemas']['LogTopic'];
export type MemberId = components['schemas']['MemberId'];
export type PaginationMetadata = components['schemas']['PaginationMetadata'];
export type PostHogErrorTrackingLogStreamConfig = components['schemas']['PostHogErrorTrackingLogStreamConfig'];
export type PostHogLogsLogStreamConfig = components['schemas']['PostHogLogsLogStreamConfig'];
export type ProjectId = components['schemas']['ProjectId'];
export type RequestDestination = components['schemas']['RequestDestination'];
export type RotateLogStreamSecretResponse = components['schemas']['RotateLogStreamSecretResponse'];
export type SentryLogStreamConfig = components['schemas']['SentryLogStreamConfig'];
export type TeamId = components['schemas']['TeamId'];
export type UpdateAxiomSinkArgs = components['schemas']['UpdateAxiomSinkArgs'];
export type UpdateCanonicalUrlRequest = components['schemas']['UpdateCanonicalUrlRequest'];
export type UpdateDatadogSinkArgs = components['schemas']['UpdateDatadogSinkArgs'];
export type UpdateEnvVarRequest = components['schemas']['UpdateEnvVarRequest'];
export type UpdateEnvVarsRequest = components['schemas']['UpdateEnvVarsRequest'];
export type UpdateLogStreamArgs = components['schemas']['UpdateLogStreamArgs'];
export type UpdatePostHogErrorTrackingSinkArgs = components['schemas']['UpdatePostHogErrorTrackingSinkArgs'];
export type UpdatePostHogLogsSinkArgs = components['schemas']['UpdatePostHogLogsSinkArgs'];
export type UpdateSentrySinkArgs = components['schemas']['UpdateSentrySinkArgs'];
export type UpdateWebhookSinkArgs = components['schemas']['UpdateWebhookSinkArgs'];
export type UsageLimitConfigRequest = components['schemas']['UsageLimitConfigRequest'];
export type UsageLimitConfigResponse = components['schemas']['UsageLimitConfigResponse'];
export type UsageLimitResponse = components['schemas']['UsageLimitResponse'];
export type Value = components['schemas']['Value'];
export type WebhookFormat = components['schemas']['WebhookFormat'];
export type WebhookLogStreamConfig = components['schemas']['WebhookLogStreamConfig'];
export type $defs = Record<string, never>;
export interface operations {
    update_environment_variables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEnvVarsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_environment_variables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvVarsResponse"];
                };
            };
        };
    };
    list_audit_log_events: {
        parameters: {
            query: {
                /** @description Only return events on or after this time, in milliseconds since epoch.
                 *     Pass the same value on every page of a paginated request. */
                from: number;
                /** @description Maximum number of events to return (defaults to 15, capped at 100). */
                limit?: number | null;
                /** @description Cursor from a previous response to fetch the next page. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDeploymentAuditLogEventsResponse"];
                };
            };
        };
    };
    "get deployment info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentInfoResponse"];
                };
            };
        };
    };
    list_usage_limits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsageLimitsResponse"];
                };
            };
        };
    };
    create_usage_limit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsageLimitConfigRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageLimitResponse"];
                };
            };
        };
    };
    update_usage_limit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description id of the usage limit to update */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsageLimitConfigRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageLimitResponse"];
                };
            };
        };
    };
    delete_usage_limit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description id of the usage limit to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_canonical_url: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCanonicalUrlRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_canonical_urls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCanonicalUrlsResponse"];
                };
            };
        };
    };
    list_log_streams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogStreamConfig"][];
                };
            };
        };
    };
    get_log_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description id of the log stream to retrieve */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogStreamConfig"];
                };
            };
        };
    };
    delete_log_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description id of the log stream to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_log_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLogStreamArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateLogStreamResponse"];
                };
            };
        };
    };
    update_log_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description id of the log stream to update */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLogStreamArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotate_webhook_secret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description id of the webhook log stream for which to rotate the secret */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateLogStreamSecretResponse"];
                };
            };
        };
    };
    pause_deployment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unpause_deployment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    data_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataSyncArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSyncResponse"];
                };
            };
        };
    };
}
