/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/teams/{team_id}/create_project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create project
         * @description Create a new project on a team and provision a dev or prod deployment.
         */
        post: operations["create project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/list_projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description List all projects for a team.
         */
        get: operations["list projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/list_deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List deployments
         * @description List deployments for a projects.
         */
        get: operations["list deployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete project
         * @description Delete a project. Deletes all deployments in the project as well.
         */
        post: operations["delete project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/create_deploy_key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create deploy key
         * @description Create a deploy key like "dev:happy-animal-123|ey..." which can be
         *     used with the Convex CLI to develop against or deploy code.
         *
         *     When access to the deployment is granted through an OAuth token this
         *     deploy key will use the same OAuth-granted token.
         *
         *     When access to the deployment is granted any other way a new token will be
         *     created which grants access only to this deployment.
         */
        post: operations["create deploy key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token_details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get token details
         * @description Returns the team ID for team tokens.
         *     Especially useful after receiving a team token from an OAuth flow
         *     since most endpoints require team ID.
         */
        get: operations["get token details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/create_custom_domain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create custom domain */
        post: operations["create custom domain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/delete_custom_domain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete custom domain
         * @description Remove a custom domain from a deployment.
         */
        post: operations["delete custom domain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{deployment_name}/custom_domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List custom domains
         * @description Get all custom domains configured for a deployment.
         */
        get: operations["list custom domains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Encrypted admin key */
        AdminKey: string;
        /** @enum {string} */
        DeploymentType: "dev" | "prod" | "preview";
        DeviceName: string;
        PlatformCreateDeployKeyArgs: {
            /** @description Name for the deploy key. */
            name: string;
        };
        PlatformCreateDeployKeyResponse: {
            /** @description The generated deploy key. */
            deployKey: components["schemas"]["AdminKey"];
        };
        PlatformCreateProjectArgs: {
            /** @description Projects always include a deployment, so start this project off with a
             *     "dev" development deployment or a "prod" production deployment. */
            deploymentType: components["schemas"]["PlatformProjectDeploymentType"];
            /** @description The full name of the project as it will appear in the dashboard. Spaces
             *     and punctuations allowed. */
            projectName: components["schemas"]["ProjectName"];
        };
        PlatformCreateProjectResponse: {
            /** @description The readable identifier for this deployment, something like
             *     playful-otter-123. */
            deploymentName: string;
            /** @description Deployment cloud URL, where this deployment lives. */
            deploymentUrl: string;
            projectId: components["schemas"]["ProjectId"];
        };
        PlatformCustomDomainResponse: {
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this domain was created.
             */
            creationTime: number;
            /** @description The deployment name this domain is configured for. */
            deploymentName: string;
            /** @description The custom domain name. */
            domain: string;
            /** @description The destination for this custom domain (convexCloud or convexSite). */
            requestDestination: components["schemas"]["RequestDestination"];
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this domain was verified, or null if not
             *     yet verified.
             */
            verificationTime?: number | null;
        };
        PlatformDeleteCustomDomainArgs: {
            /** @description The custom domain name to delete. */
            domain: string;
            /** @description The destination for this custom domain (convexCloud or convexSite). */
            requestDestination: components["schemas"]["RequestDestination"];
        };
        PlatformDeploymentResponse: {
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this deployment was created.
             */
            createTime: number;
            /** @description Whether this is a "dev" development deployment or "prod" production
             *     deployment. */
            deploymentType: components["schemas"]["DeploymentType"];
            /** @description The readable identifier for this deployment, something like
             *     playful-otter-123. */
            name: string;
            previewIdentifier?: null | components["schemas"]["PreviewDeploymentIdentifier"];
            /** @description The project this deployment belongs to. */
            projectId: components["schemas"]["ProjectId"];
        };
        PlatformListCustomDomainsResponse: {
            /** @description List of custom domains configured for this deployment. */
            domains: components["schemas"]["PlatformCustomDomainResponse"][];
        };
        /** @enum {string} */
        PlatformProjectDeploymentType: "dev" | "prod";
        PlatformProjectDetails: {
            /**
             * Format: int64
             * @description Timestamp in milliseconds.
             */
            createTime: number;
            id: components["schemas"]["ProjectId"];
            /** @description The full project name, including spaces and punctuation. */
            name: components["schemas"]["ProjectName"];
            /** @description This shortened version of the name used in Convex Dashboard URLs. */
            slug: components["schemas"]["ProjectSlug"];
            teamId: components["schemas"]["TeamId"];
        };
        PlatformTokenDetailsResponse: {
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this token was created.
             */
            createTime: number;
            /** @description The name given to the token at creation. */
            name: components["schemas"]["DeviceName"];
            /** @description The team ID this token is associated with. */
            teamId: components["schemas"]["TeamId"];
            /** @enum {string} */
            type: "teamToken";
        } | {
            /**
             * Format: int64
             * @description Timestamp in milliseconds when this token was created.
             */
            createTime: number;
            /** @description The name given to the token at creation. */
            name: components["schemas"]["DeviceName"];
            /** @description The project ID this token is associated with. */
            projectId: components["schemas"]["ProjectId"];
            /** @enum {string} */
            type: "projectToken";
        };
        PreviewDeploymentIdentifier: string;
        /** Format: int64 */
        ProjectId: number;
        ProjectName: string;
        ProjectSlug: string;
        /** @enum {string} */
        RequestDestination: "convexCloud" | "convexSite";
        /** Format: int64 */
        TeamId: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AdminKey = components['schemas']['AdminKey'];
export type DeploymentType = components['schemas']['DeploymentType'];
export type DeviceName = components['schemas']['DeviceName'];
export type PlatformCreateDeployKeyArgs = components['schemas']['PlatformCreateDeployKeyArgs'];
export type PlatformCreateDeployKeyResponse = components['schemas']['PlatformCreateDeployKeyResponse'];
export type PlatformCreateProjectArgs = components['schemas']['PlatformCreateProjectArgs'];
export type PlatformCreateProjectResponse = components['schemas']['PlatformCreateProjectResponse'];
export type PlatformCustomDomainResponse = components['schemas']['PlatformCustomDomainResponse'];
export type PlatformDeleteCustomDomainArgs = components['schemas']['PlatformDeleteCustomDomainArgs'];
export type PlatformDeploymentResponse = components['schemas']['PlatformDeploymentResponse'];
export type PlatformListCustomDomainsResponse = components['schemas']['PlatformListCustomDomainsResponse'];
export type PlatformProjectDeploymentType = components['schemas']['PlatformProjectDeploymentType'];
export type PlatformProjectDetails = components['schemas']['PlatformProjectDetails'];
export type PlatformTokenDetailsResponse = components['schemas']['PlatformTokenDetailsResponse'];
export type PreviewDeploymentIdentifier = components['schemas']['PreviewDeploymentIdentifier'];
export type ProjectId = components['schemas']['ProjectId'];
export type ProjectName = components['schemas']['ProjectName'];
export type ProjectSlug = components['schemas']['ProjectSlug'];
export type RequestDestination = components['schemas']['RequestDestination'];
export type TeamId = components['schemas']['TeamId'];
export type $defs = Record<string, never>;
export interface operations {
    "create project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID */
                team_id: components["schemas"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformCreateProjectArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformCreateProjectResponse"];
                };
            };
        };
    };
    "list projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team ID */
                team_id: components["schemas"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformProjectDetails"][];
                };
            };
        };
    };
    "list deployments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformDeploymentResponse"][];
                };
            };
        };
    };
    "delete project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                project_id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "create deploy key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformCreateDeployKeyArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformCreateDeployKeyResponse"];
                };
            };
        };
    };
    "get token details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformTokenDetailsResponse"];
                };
            };
        };
    };
    "create custom domain": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformDeleteCustomDomainArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "delete custom domain": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformDeleteCustomDomainArgs"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "list custom domains": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Deployment name */
                deployment_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformListCustomDomainsResponse"];
                };
            };
        };
    };
}
