import { z } from "zod";
import { ConvexTool } from "./index.js";
import { loadSelectedDeploymentCredentials } from "../../api.js";
import {
  RUN_ONEOFF_MUTATION_SOURCE_DESCRIPTION,
  runTestFunctionMutation,
} from "../../runTestFunction.js";
import { ThrowingFetchError } from "../../utils/utils.js";
import { getMcpDeploymentSelection } from "../requestContext.js";

const inputSchema = z.object({
  deploymentSelector: z
    .string()
    .describe(
      "Deployment selector (from the status tool) to run the mutation on.",
    ),
  mutation: z.string().describe(RUN_ONEOFF_MUTATION_SOURCE_DESCRIPTION),
});

const outputSchema = z.object({
  result: z.any().describe("The result returned by the mutation"),
  logLines: z
    .array(z.string())
    .describe("The log lines generated by the mutation"),
});

const description = `
Run a one-off mutation on your Convex deployment.

This tool executes a JavaScript string as a mutation in your Convex deployment.
The mutation should follow Convex guidelines and use the following setup:

\`\`\`js
import { mutation, internalMutation } from "convex:/_system/repl/wrappers.js";

export default mutation({
  handler: async (ctx) => {
    console.log("Write and test your mutation function here!");
  },
});
\`\`\`

Note that there are no imports available in this environment. The only import
you can use is the built-in "convex:/_system/repl/wrappers.js" module in the
template.

The function call runs in the usual Convex mutation environment. It can modify
the database, but it still cannot access the network.

Returns the result and any log lines generated by the mutation.
`.trim();

export const RunOneoffMutationTool: ConvexTool<
  typeof inputSchema,
  typeof outputSchema
> = {
  name: "runOneoffMutation",
  description,
  inputSchema,
  outputSchema,
  handler: async (ctx, args) => {
    const { projectDir, deployment } = await ctx.decodeDeploymentSelector(
      args.deploymentSelector,
    );
    process.chdir(projectDir);
    const deploymentSelection = await getMcpDeploymentSelection(
      ctx,
      deployment,
    );
    const credentials = await loadSelectedDeploymentCredentials(
      ctx,
      deploymentSelection,
    );
    try {
      const outcome = await runTestFunctionMutation(ctx, {
        deploymentUrl: credentials.url,
        adminKey: credentials.adminKey,
        mutationSource: args.mutation,
      });
      if (outcome.kind === "applicationFailure") {
        return await ctx.crash({
          exitCode: 1,
          errorType: "fatal",
          printedMessage: `Mutation failed: ${JSON.stringify(outcome.payload, null, 2)}`,
        });
      }
      return {
        result: outcome.value,
        logLines: outcome.logLines,
      };
    } catch (err) {
      if (err instanceof ThrowingFetchError) {
        return await err.handle(ctx);
      }
      return await ctx.crash({
        exitCode: 1,
        errorType: "fatal",
        printedMessage: `Failed to run mutation: ${(err as Error).toString().trim()}`,
      });
    }
  },
};
