[package]
name = "orchestrator_api_types"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
big_brain_private_api_types = { workspace = true }
chrono = { workspace = true }
common = { workspace = true }
keybroker = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
tuple_struct = { workspace = true }
utoipa = { workspace = true }

[lints]
workspace = true
