[package]
name = "keybroker"
version = "0.1.0"
authors = ["Convex, Inc. <no-reply@convex.dev>"]
edition = "2021"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
chrono = { workspace = true }
cmd_util = { path = "../cmd_util" }
common = { path = "../common" }
derive_more = { workspace = true }
errors = { path = "../errors" }
hex = { workspace = true }
metrics = { path = "../metrics" }
openidconnect = { workspace = true }
pb = { path = "../pb" }
proptest = { workspace = true }
proptest-derive = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
rsa = { workspace = true, optional = true }
serde = { workspace = true }
sodiumoxide = { workspace = true }
sync_types = { package = "convex_sync_types", path = "../convex/sync_types" }
tracing = { workspace = true }

[dev-dependencies]
common = { path = "../common", features = ["testing"] }
errors = { path = "../errors", features = ["testing"] }
metrics = { path = "../metrics", features = ["testing"] }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rsa = { workspace = true }
runtime = { path = "../runtime", features = ["testing"] }

[features]
testing = [
    "common/testing",
    "errors/testing",
    "metrics/testing",
    "rsa",
    "runtime/testing",
]

[lints]
workspace = true
