import { Meta, StoryObj } from "@storybook/nextjs";
import { PlatformDeploymentResponse } from "@convex-dev/platform/managementApi";
import { ProjectDetails } from "generatedApi";
import { AggregatedFunctionMetricsV2 } from "hooks/usageMetricsV2";
import { rootComponentPath } from "api/usage";
import { Sheet } from "@ui/Sheet";
import {
  FunctionBreakdownMetricCallsV2,
  FunctionBreakdownMetricComputeV2,
  FunctionBreakdownMetricDatabaseIOV2,
  FunctionBreakdownMetricDataEgressV2,
  FunctionBreakdownMetricSearchV2,
  TeamUsageByFunctionChart,
} from "./TeamUsageByFunctionChart";

const meta = {
  component: TeamUsageByFunctionChart,
  render: (args) => (
    <Sheet>
      <TeamUsageByFunctionChart {...args} />
    </Sheet>
  ),
  parameters: { a11y: { test: "todo" } },
} satisfies Meta<typeof TeamUsageByFunctionChart>;

export default meta;
type Story = StoryObj<typeof meta>;

const team = {
  id: 42,
  name: "My amazing team",
  creator: 1,
  slug: "my-amazing-team",
  suspended: false,
  referralCode: "MYAMAZ1341",
  referredBy: null,
};

const project: ProjectDetails = {
  id: 42,
  teamId: 42,
  slug: "my-project",
  name: "My Project",
  isDemo: false,
  createTime: 0,
};

const deployments: PlatformDeploymentResponse[] = [
  {
    kind: "cloud",
    id: 10,
    projectId: 42,
    name: "fabulous-goldfish-42",
    deploymentUrl: "https://fabulous-goldfish-42.convex.cloud",
    deploymentType: "dev",
    createTime: 0,
    creator: 1,
    previewIdentifier: null,
    region: "aws-us-east-1",
    isDefault: true,
    reference: "dev/nicolas",
    class: "s16",
  },
  {
    kind: "cloud",
    id: 20,
    projectId: 42,
    name: "friendly-dog-64",
    deploymentUrl: "https://friendly-dog-64.convex.cloud",
    deploymentType: "dev",
    createTime: 0,
    creator: 2,
    previewIdentifier: null,
    region: "aws-us-east-1",
    isDefault: true,
    reference: "dev/ari",
    class: "s16",
  },
  {
    kind: "cloud",
    id: 30,
    projectId: 42,
    name: "wandering-fish-513",
    deploymentUrl: "https://wandering-fish-513.convex.cloud",
    deploymentType: "prod",
    createTime: 0,
    creator: 1,
    previewIdentifier: null,
    region: "aws-us-east-1",
    isDefault: true,
    reference: "production",
    class: "s16",
  },
  {
    kind: "cloud",
    id: 40,
    projectId: 42,
    name: "happy-capybara-123",
    deploymentUrl: "https://happy-capybara-123.convex.cloud",
    deploymentType: "custom",
    createTime: 0,
    creator: 1,
    previewIdentifier: null,
    region: "aws-us-east-1",
    isDefault: false,
    reference: "staging",
    class: "s16",
  },
];

const rows: AggregatedFunctionMetricsV2[] = [
  {
    projectId: 42,
    deploymentName: "wandering-fish-513",
    function: "module.js:getLeague",
    callCount: 1,
    databaseIngressSize: 349567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "wandering-fish-513",
    function: "folder/module.js:setProfile",
    callCount: 10_000,
    databaseIngressSize: 67,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "wandering-fish-513",
    function: "module.js:thisFunctionHasAReallyLongName",
    callCount: 2_000,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "happy-capybara-123",
    function: "module.js:thisFunctionHasAReallyLongName",
    callCount: 23_456,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 1234,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 5678,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "wandering-fish-513",
    function: "module.js:setAvatar",
    callCount: 9_000,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "friendly-dog-64",
    function: "module.js:getBalls",
    callCount: 1_000,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "friendly-dog-64",
    function: "/api/endpoint",
    callCount: 12345,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 98765,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "fabulous-goldfish-42",
    function: "devMerge.js:example",
    callCount: 40,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "wandering-fish-513",
    function: "folder/module.js:setScore",
    callCount: 16_000,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "wandering-fish-513",
    function: "module.js:default",
    callCount: 21_034,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 20,
    vectorSearchGb: 10,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "friendly-dog-64",
    function: "devMerge.js:example",
    callCount: 2,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 10,
    vectorSearchGb: 50,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 2,
    deploymentName: "former-deployment-31",
    function: "former_project_function.js:default",
    callCount: 22_022,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "wandering-fish-513",
    function: "module.js:getBalls",
    callCount: 25_431,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0,
    actionComputeConvexTime: 0,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "wandering-fish-513",
    function: "module.js:getBall",
    callCount: 30_000,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0.0012,
    actionComputeConvexTime: 0.0011,
    actionComputeNodeTime: 0,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "wandering-fish-513",
    function: "folder/module.js:getScore",
    callCount: 20_000,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 0.1,
    actionComputeConvexTime: 0.02,
    actionComputeNodeTime: 0.003,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
  {
    projectId: 42,
    deploymentName: "friendly-dog-64",
    function: "folder/module.js:getScore",
    callCount: 200,
    databaseIngressSize: 34567,
    databaseEgressSize: 12345,
    textSearchGb: 0,
    vectorSearchGb: 0,
    queryMutationComputeTime: 12.4,
    actionComputeConvexTime: 10.0,
    actionComputeNodeTime: 10.0456778,
    dataEgress: 0,
    componentPath: rootComponentPath,
  },
];

export const Default: Story = {
  args: {
    rows,
    team,
    project,
    deployments,
    maxValue: Math.max(...rows.map(FunctionBreakdownMetricCallsV2.getTotal)),
    metric: FunctionBreakdownMetricCallsV2,
  },
};

export const ForDeletedProject: Story = {
  args: {
    rows,
    team,
    project: null,
    deployments: [],
    maxValue: Math.max(...rows.map(FunctionBreakdownMetricCallsV2.getTotal)),
    metric: FunctionBreakdownMetricCallsV2,
  },
};

export const DatabaseIO: Story = {
  args: {
    rows,
    team,
    project,
    deployments,
    maxValue: Math.max(
      ...rows.map(FunctionBreakdownMetricDatabaseIOV2.getTotal),
    ),
    metric: FunctionBreakdownMetricDatabaseIOV2,
  },
};

export const Compute: Story = {
  args: {
    rows,
    team,
    project,
    deployments,
    maxValue: Math.max(...rows.map(FunctionBreakdownMetricComputeV2.getTotal)),
    metric: FunctionBreakdownMetricComputeV2,
  },
};

export const Search: Story = {
  args: {
    rows,
    team,
    project,
    deployments,
    maxValue: Math.max(...rows.map(FunctionBreakdownMetricSearchV2.getTotal)),
    metric: FunctionBreakdownMetricSearchV2,
  },
};

export const DataEgress: Story = {
  args: {
    rows,
    team,
    project,
    deployments,
    maxValue: Math.max(
      ...rows.map(FunctionBreakdownMetricDataEgressV2.getTotal),
    ),
    metric: FunctionBreakdownMetricDataEgressV2,
  },
};
