[package]
name = "orchestrator"
version = "0.1.0"
edition = "2024"
license = "LicenseRef-FSL-1.1-Apache-2.0"

[[bin]]
name = "convex-orchestrator"
path = "src/main.rs"

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
base32 = { workspace = true }
base64 = { workspace = true }
big_brain_private_api_types = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
common = { workspace = true }
orchestrator_api_types = { workspace = true }
fastrand = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
httparse = "1.10"
hyper = { workspace = true }
hyper-util = { workspace = true, features = ["server", "http1", "client", "client-legacy"] }
instant-acme = { workspace = true }
keybroker = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sha2 = { workspace = true }
slugify = { workspace = true }
sodium_secretbox = { workspace = true }
strum = { workspace = true }
sysinfo = "0.33"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
tokio-postgres-rustls = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
url = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }

[build-dependencies]
syn = { version = "2", features = ["full", "extra-traits", "visit"] }

[lints]
workspace = true
