FROM node:18

WORKDIR /app

# Clone the repository
RUN git clone https://github.com/get-convex/convex-backend.git .

# Install dependencies and build
WORKDIR /app/npm-packages/dashboard-common
RUN npm install -g @microsoft/rush
RUN rush update

EXPOSE 6790
# TODO: Use production command here
CMD ["npm", "run", "dev"]
