name: Metrics
on:
  workflow_run:
    workflows:
      - "**"
    types:
      - completed

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: int128/datadog-actions-metrics@262ee4930e40245b2d9806da14213982073ae952 # v1
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          collect-job-metrics: true
